### ISSUE TITLE
[2] - Setup Kanban board

### ISSUE THREAD

**Issue by Jawad-Nazari** [Jawad-Nazari/Recipe-app#13]
### In this PR, we did the following:
Covered the following [project requirements](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md) 👇 

Create an empty repository for your group project.
Open the GitHub project (Kanban board) in your team repo
Create tasks on your Kanban board based on the [project requirements](https://github.com/KanzaTahreem/Recipe-App/issues/buisness_requirements.md).
Each task should be a separate card with descriptive title and number of points in the [Xpt] prefix
Each of the team members should assign themselves to the cards.
Decide who will be the assignee for the cards marked as group tasks. All cards on your Kanban board should have assignees.
[Open a new issue in your repository](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue) and send it for review
Project Link 🔗
Here is the link for [Kanban board](https://github.com/users/Jawad-Nazari/projects/3) created for the project

Group Members:
@Jawad-Nazari
@Victoria129

**Comment by TedLivist** [comment]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @Victoria129 and @Jawad-Nazari,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### I cannot access your project. Kindly look into that.

![image](https://github.com/Jawad-Nazari/Recipe-app/assets/36542986/393d3f45-134d-4f75-9331-3a989ad1e65d)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by bobb-Rob** [comment]
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ All linters checks are ok
✅ The correct workflow is used. 
✅ Very descriptive Pull Request(PR)
✅ Your work is well documented.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏
